(() => {
const ACTIONS = Object.freeze({
  DRAW_CARD: "DRAW_CARD",
  PLAY_CARD: "PLAY_CARD",
  CONFIRM_PLAY: "CONFIRM_PLAY",
  CONFIRM_DRAW: "CONFIRM_DRAW",
  CONFIRM_METEOR: "CONFIRM_METEOR",
  CONFIRM_PEEK: "CONFIRM_PEEK",
  CONFIRM_STEAL: "CONFIRM_STEAL",
  PLACE_METEOR: "PLACE_METEOR",
  DIG_CHOICE: "DIG_CHOICE",
  ORDER_ORACLE: "ORDER_ORACLE",
  PTERO_CHOICE: "PTERO_CHOICE",
  CHOOSE_TARGET: "CHOOSE_TARGET",
  ATTACK_PASS: "ATTACK_PASS",
  ATTACK_NOPE: "ATTACK_NOPE",
  ATTACK_REFLECT: "ATTACK_REFLECT",
  NOPE_PLAY: "NOPE_PLAY",
  NOPE_PASS: "NOPE_PASS",
  CHOOSE_FOSSIL_TARGET: "CHOOSE_FOSSIL_TARGET",
  CHOOSE_FOSSIL_CARD: "CHOOSE_FOSSIL_CARD",
  CHOOSE_MINI_TARGET: "CHOOSE_MINI_TARGET",
  CHOOSE_DISCARD: "CHOOSE_DISCARD",
  BRONTO_CHOICE: "BRONTO_CHOICE"
});

const INTERACTIONS = Object.freeze({
  WAITING: "WAITING",
  PLAY_REVEAL: "PLAY_REVEAL",
  DRAW_REVEAL: "DRAW_REVEAL",
  METEOR_REVEAL: "METEOR_REVEAL",
  METEOR_PLACEMENT: "METEOR_PLACEMENT",
  PEEK: "PEEK",
  TARGET_CHOICE: "TARGET_CHOICE",
  ATTACK_REACTION: "ATTACK_REACTION",
  NOPE_RESPONSE: "NOPE_RESPONSE",
  FOSSIL_TARGET: "FOSSIL_TARGET",
  FOSSIL_CARD: "FOSSIL_CARD",
  MINI_TARGET: "MINI_TARGET",
  STEAL_REVEAL: "STEAL_REVEAL",
  DIG_CHOICE: "DIG_CHOICE",
  DISCARD_PICK: "DISCARD_PICK",
  BRONTO_CHOICE: "BRONTO_CHOICE",
  ORACLE_ORDER: "ORACLE_ORDER",
  PTERO_CHOICE: "PTERO_CHOICE"
});

const choiceActions = new Set(Object.values(ACTIONS).filter((type) => type !== ACTIONS.DRAW_CARD && type !== ACTIONS.PLAY_CARD));
const isChoiceAction = (type) => choiceActions.has(type);

const protocol = { ACTIONS, INTERACTIONS, isChoiceAction };
globalThis.ExplodingDinosProtocol = protocol;
if (typeof module !== "undefined" && module.exports) module.exports = protocol;
})();
